package main

// Estonian morphology labels and code selections

var morphLabels = map[string]string{
	// Singular noun cases
	"SgN":   "ainsuse nimetav",
	"SgG":   "ainsuse omastav",
	"SgP":   "ainsuse osastav",
	"SgAdt": "ainsuse lühike sisseütlev",
	"SgIll": "ainsuse sisseütlev",
	"SgIn":  "ainsuse seesütlev",
	"SgEl":  "ainsuse seestütlev",
	"SgAll": "ainsuse alaleütlev",
	"SgAd":  "ainsuse alalütlev",
	"SgAbl": "ainsuse alaltütlev",
	"SgTr":  "ainsuse saav",
	"SgTer": "ainsuse rajav",
	"SgEs":  "ainsuse olev",
	"SgAb":  "ainsuse ilmaütlev",
	"SgKom": "ainsuse kaasaütlev",
	// Plural noun cases
	"PlN":   "mitmuse nimetav",
	"PlG":   "mitmuse omastav",
	"PlP":   "mitmuse osastav",
	"PlIll": "mitmuse sisseütlev",
	"PlIn":  "mitmuse seesütlev",
	"PlEl":  "mitmuse seestütlev",
	"PlAll": "mitmuse alaleütlev",
	"PlAd":  "mitmuse alalütlev",
	"PlAbl": "mitmuse alaltütlev",
	"PlTr":  "mitmuse saav",
	"PlTer": "mitmuse rajav",
	"PlEs":  "mitmuse olev",
	"PlAb":  "mitmuse ilmaütlev",
	"PlKom": "mitmuse kaasaütlev",
	"Rpl":   "mitmuse tüvi",
	// Verb forms
	"Sup":         "ma-tegevusnimi",
	"SupAb":       "ma-tegevusnimi ilmaütlev",
	"SupIn":       "ma-tegevusnimi seesütlev",
	"SupEl":       "ma-tegevusnimi seestütlev",
	"SupTr":       "ma-tegevusnimi saav",
	"SupIps":      "ma-tegevusnimi umbisikuline",
	"Inf":         "da-tegevusnimi",
	"Ger":         "des-vorm",
	"PtsPrPs":     "oleviku kesksõna isikuline",
	"PtsPrIps":    "oleviku kesksõna umbisikuline",
	"PtsPtPs":     "mineviku kesksõna isikuline",
	"PtsPtPsNeg":  "mineviku kesksõna isikuline eitav",
	"PtsPtIps":    "mineviku kesksõna umbisikuline",
	"PtsPtIpsNeg": "mineviku kesksõna umbisikuline eitav",
	"IndPrSg1":    "kindel kõneviis olevikus 1.p ainsus",
	"IndPrSg2":    "kindel kõneviis olevikus 2.p ainsus",
	"IndPrSg3":    "kindel kõneviis olevikus 3.p ainsus",
	"IndPrPl1":    "kindel kõneviis olevikus 1.p mitmus",
	"IndPrPl2":    "kindel kõneviis olevikus 2.p mitmus",
	"IndPrPl3":    "kindel kõneviis olevikus 3.p mitmus",
	"IndPrIps":    "kindel kõneviis olevikus umbisikuline",
	"IndPrIpsNeg": "kindel kõneviis olevikus umbisikuline eitav",
	"IndIpfSg1":   "kindel kõneviis minevikus 1.p ainsus",
	"IndIpfSg2":   "kindel kõneviis minevikus 2.p ainsus",
	"IndIpfSg3":   "kindel kõneviis minevikus 3.p ainsus",
	"IndIpfPl1":   "kindel kõneviis minevikus 1.p mitmus",
	"IndIpfPl2":   "kindel kõneviis minevikus 2.p mitmus",
	"IndIpfPl3":   "kindel kõneviis minevikus 3.p mitmus",
	"IndIpfIps":   "kindel kõneviis minevikus umbisikuline",
	"KndPrSg1":    "tingiv kõneviis olevikus 1.p ainsus",
	"KndPrSg2":    "tingiv kõneviis olevikus 2.p ainsus",
	"KndPrSg3":    "tingiv kõneviis olevikus 3.p ainsus",
	"KndPrPl1":    "tingiv kõneviis olevikus 1.p mitmus",
	"KndPrPl2":    "tingiv kõneviis olevikus 2.p mitmus",
	"KndPrPl3":    "tingiv kõneviis olevikus 3.p mitmus",
	"KndPrIps":    "tingiv kõneviis olevikus umbisikuline",
	"KndPtSg1":    "tingiv kõneviis minevikus 1.p ainsus",
	"KndPtSg2":    "tingiv kõneviis minevikus 2.p ainsus",
	"KndPtSg3":    "tingiv kõneviis minevikus 3.p ainsus",
	"KndPtPl1":    "tingiv kõneviis minevikus 1.p mitmus",
	"KndPtPl2":    "tingiv kõneviis minevikus 2.p mitmus",
	"KndPtPl3":    "tingiv kõneviis minevikus 3.p mitmus",
	"KndPtIps":    "tingiv kõneviis minevikus umbisikuline",
	"KvtPrSg2":    "käskiv kõneviis 2.p ainsus",
	"KvtPrPl1":    "käskiv kõneviis 1.p mitmus",
	"KvtPrPl2":    "käskiv kõneviis 2.p mitmus",
	"KvtPrIps":    "käskiv kõneviis umbisikuline",
	"Neg":         "eitav vorm",
}

var nounMorphCodes = []string{"SgN", "SgG", "SgP", "PlP"}
var verbMorphCodes = []string{"Sup", "Inf", "IndPrSg3", "PtsPtIps"}
